### PR TITLE
(#233) Fix for blog series tests

### LINKED ISSUE #233: Update blog posts for redesign
*Description of what is to be accomplished.*

**Parent Issue:** #9999

### Sub-Tasks
- [ ] Create Component
- [ ] Implement Unit Tests for Component

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

### PR DESCRIPTION
**Pull request by ahmadakbaryNIH**
-I've emplemented one step definition.

Closes #233

### CODE REVIEW

File: cypress/e2e/FilteringBlogsByYear/index.js [hunk 1]
```diff
@@ -0,0 +1,18 @@
+/// <reference types="Cypress" />
+import { Given, And, Then } from 'cypress-cucumber-preprocessor/steps';
```
Comment (KateMashkinaNIH) [inline cypress/e2e/FilteringBlogsByYear/index.js:2]: What is this file? Delete it please

**Review by KateMashkinaNIH — CHANGES_REQUESTED** [review]

**Comment by KateMashkinaNIH** [comment]
So looks like your interactive rebased went a bit too far.. I am going to fix up your commits

**Review by KateMashkinaNIH — APPROVED** [review]
